theme = "catppuccin_mocha"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor]
# auto-save = true
auto-completion = false
# auto-format = true
